name: TitanPunishments
version: ${project.version}
description: ${project.description}
main: dev.titanlabs.punishment.PunishmentPlugin
api-version: '1.13'
authors: [Zak Shearman, Hyfe]
website: www.titanlabs.dev

commands:
  titanpunish:
    description: Informative Command
    aliases:
      - titanpunishments
      - punishments
  ban:
    description: Ban a player
    aliases:
      - banish
  unban:
    description: Unban a player
    aliases:
      - pardon