name: TitanPunishments
version: ${project.version}
description: ${project.description}
main: dev.titanlabs.punishment.PunishmentPlugin
api-version: '1.13'
authors: [Zak Shearman, Hyfe]
website: www.titanlabs.dev

commands: []