name: TitanPunishment
version: ${project.version}
main: dev.titanlabs.punishment.Punishment
api-version: '1.13'
authors: [Zak Shearman, Hyfe]
website: www.titanlabs.dev

commands:
  titanpunish:
    description: Informative Command
    aliases:
      - titanpunishments
      - punishments
  ban:
    description: Ban command
    aliases:
      - banish
